allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - 'hoshimi'
  - seyfert
  - '@biomejs/biome@2.5.4 || 2.5.5 || 2.5.7 || 2.5.8 || 2.5.9 || 2.5.10'
  - '@biomejs/cli-darwin-arm64@2.5.4 || 2.5.5 || 2.5.7 || 2.5.8 || 2.5.9 || 2.5.10'
  - '@biomejs/cli-darwin-x64@2.5.4 || 2.5.5 || 2.5.7 || 2.5.8 || 2.5.9 || 2.5.10'
  - '@biomejs/cli-linux-arm64-musl@2.5.4 || 2.5.5 || 2.5.7 || 2.5.8 || 2.5.9 || 2.5.10'
  - '@biomejs/cli-linux-arm64@2.5.4 || 2.5.5 || 2.5.7 || 2.5.8 || 2.5.9 || 2.5.10'
  - '@biomejs/cli-linux-x64-musl@2.5.4 || 2.5.5 || 2.5.7 || 2.5.8 || 2.5.9 || 2.5.10'
  - '@biomejs/cli-linux-x64@2.5.4 || 2.5.5 || 2.5.7 || 2.5.8 || 2.5.9 || 2.5.10'
  - '@biomejs/cli-win32-arm64@2.5.4 || 2.5.5 || 2.5.7 || 2.5.8 || 2.5.9 || 2.5.10'
  - '@biomejs/cli-win32-x64@2.5.4 || 2.5.5 || 2.5.7 || 2.5.8 || 2.5.9 || 2.5.10'
  - yunaforseyfert@1.2.3
  - lint-staged@17.1.1 || 17.2.0 || 17.3.0
  - '@redis/client@6.2.0 || 6.2.1'
  - tsx@4.23.9
  - '@types/node@26.2.0'

packages: []
