allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - '@biomejs/biome@2.4.16'
  - '@biomejs/cli-darwin-arm64@2.4.16'
  - '@biomejs/cli-darwin-x64@2.4.16'
  - '@biomejs/cli-linux-arm64-musl@2.4.16'
  - '@biomejs/cli-linux-arm64@2.4.16'
  - '@biomejs/cli-linux-x64-musl@2.4.16'
  - '@biomejs/cli-linux-x64@2.4.16'
  - '@biomejs/cli-win32-arm64@2.4.16'
  - '@biomejs/cli-win32-x64@2.4.16'
  - 'hoshimi'

packages: []
