import { LoadType, type PlayerStructure, type QueryResult, type TrackStructure } from "hoshimi";
import type { AllGuildVoiceChannels, GuildMember, LocaleString, UsingClient } from "seyfert";
import type { TrackUser } from "#stelle/types";
import { TrackOps } from "#stelle/utils/functions/internal/track.js";
import { joinVoiceChannel } from "#stelle/utils/functions/manager/voice.js";

/**
 * The inputs needed to resolve a query into a queued/playing track for a guild.
 */
export interface PlayQueryOptions {
    /**
     * The client instance.
     * @type {UsingClient}
     */
    client: UsingClient;
    /**
     * The guild id where the player should be created and the track should be queued.
     * @type {string}
     */
    guildId: string;
    /**
     * The voice channel the player should join to play the track.
     * @type {AllGuildVoiceChannels}
     */
    voice: AllGuildVoiceChannels;
    /**
     * The bot's member object in the guild, used to join the voice channel.
     * @type {GuildMember}
     */
    me: GuildMember;
    /**
     * The text channel id where the track was requested, used to seed the player with a text channel for feedback.
     * @type {string}
     */
    textId: string;
    /**
     * The user who requested the track, used to seed the player with a requester for feedback.
     * @type {TrackUser}
     */
    requester: TrackUser;
    /**
     * The query string to resolve into a track or playlist. This can be a search term, a direct URL, or any other input that the player can handle.
     * @type {string}
     */
    query: string;
    /**
     * The locale string to use for any feedback messages or embeds generated by the player.
     * @type {LocaleString}
     */
    localeString: LocaleString;
    /**
     * Whether the request was made in a designated request channel. If true, the player will mark itself as a request channel player, which may affect how it behaves or what feedback it provides.
     * @type {boolean}
     * @default false
     */
    isRequestChannel?: boolean;
}

/**
 * The result of {@link playQuery}: the player plus the raw search outcome, so each caller renders its own reply.
 */
export interface PlayQueryResult {
    /**
     * The player instance that was created or retrieved for the guild, now containing the queued track(s).
     * @type {PlayerStructure}
     */
    player: PlayerStructure;
    /**
     * The type of load that occurred when resolving the query: Track, Search, Playlist, or an error/empty result.
     * @type {LoadType}
     */
    loadType: LoadType;
    /**
     * The playlist information if the query resolved to a playlist; otherwise null. This includes the playlist name, author, and other metadata.
     * @type {QueryResult["playlist"] | null}
     */
    playlist: QueryResult["playlist"];
    /**
     * The array of tracks that were resolved from the query. This may be empty if the load type was an error or empty result.
     * @type {TrackStructure[]}
     */
    tracks: TrackStructure[];
}

/**
 * The shared "create the player, join, search, enqueue and play" core used by both the `/play` command and the request
 * channel listener. It performs the player-side work only; the caller renders its own feedback from the result.
 * @param {PlayQueryOptions} options The resolution inputs.
 * @returns {Promise<PlayQueryResult>} The player and the raw search outcome.
 */
export async function playQuery(options: PlayQueryOptions): Promise<PlayQueryResult> {
    const { client, guildId, voice, me, textId, requester, query, localeString, isRequestChannel } = options;

    const { defaultVolume, searchPlatform } = await client.database.players.get(guildId);

    const player = client.manager.createPlayer({
        guildId,
        textId,
        voiceId: voice.id,
        volume: defaultVolume,
        selfDeaf: true,
    });

    await joinVoiceChannel(player, voice, me);

    const { loadType, playlist, tracks } = await player.search({ query, source: searchPlatform, requester });

    if (!(await player.data.get("localeString"))) await player.data.set("localeString", localeString);
    if (!(await player.data.get("me"))) await player.data.set("me", TrackOps.requesterFn(client.me));
    if (isRequestChannel) await player.data.set("isRequestChannel", true);

    const autoplayIndex: number | undefined = (await player.data.get("enabledAutoplay")) ? 0 : undefined;

    switch (loadType) {
        case LoadType.Track:
        case LoadType.Search: {
            const track: TrackStructure | undefined = tracks.at(0);
            if (track) {
                await player.queue.add(track, autoplayIndex);
                if (!player.playing) await player.play();
            }
            break;
        }
        case LoadType.Playlist: {
            if (tracks.length) {
                await player.queue.add(tracks, autoplayIndex);
                if (!player.playing) await player.play();
            }
            break;
        }
        default: {
            // Empty / Error / unknown: tear down a freshly-created idle player so we don't leave a ghost connection.
            if (!player.queue.current) await player.destroy();
            break;
        }
    }

    return { player, loadType, playlist, tracks };
}
